[package]
name = "player-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
crossbeam-channel.workspace = true
symphonia.workspace = true
symphonia-adapter-oporus.workspace = true
log.workspace = true
rubato.workspace = true
videoson.workspace = true
repose-core.workspace = true
web-time.workspace = true
baabaabaabaabababbababbaa = { git = "https://github.com/mlm-games/baa4bababab2baa", optional = true }
bytes = { version = "1", optional = true }
tokio = { version = "1", features = ["rt", "sync", "time", "macros"], optional = true }

[features]
default = []
hw = ["dep:baabaabaabaabababbababbaa", "dep:bytes", "dep:tokio", "baabaabaabaabababbababbaa/linux"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cpal.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { workspace = true, features = ["wasm-bindgen", "audioworklet"] }
js-sys.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = ["Window", "console"] }
web-workers.workspace = true
