[package]
name = "repose-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.android]
package = "org.mlm.reposeaudio"
apk_name = "repose-audio"
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi", "x86_64-linux-android", "i686-linux-android"]
split_per_abi = true
resources = "others/packaging/res"
java_sources = ["java/"]

[package.metadata.android.application]
label = "Repose Audio"
fullscreen = false
icon = "@drawable/ic_launcher_monochrome"

[package.metadata.android.sdk]
min_sdk_version = 26
target_sdk_version = 36

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[[package.metadata.android.application.activity]]
name = "org.mlm.reposeaudio.ReposeAudioActivity"
exported = true
launch_mode = "singleTask"

[[package.metadata.android.application.activity.intent_filter]]
actions = ["android.intent.action.MAIN"]
categories = ["android.intent.category.LAUNCHER"]

[[package.metadata.android.application.activity.intent_filter]]
actions = ["android.intent.action.VIEW"]
categories = ["android.intent.category.DEFAULT", "android.intent.category.BROWSABLE"]

[[package.metadata.android.application.activity.intent_filter.data]]
scheme = "content"
mime_type = "audio/*"

[[package.metadata.android.application.activity.intent_filter.data]]
scheme = "file"
mime_type = "audio/*"

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true

player-core.workspace = true
player-sync.workspace = true
player-platform.workspace = true

repose-core.workspace = true
repose-ui.workspace = true
repose-material.workspace = true
repose-platform.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
js-sys.workspace = true
web-sys = { workspace = true, features = [
    "Window",
    "HtmlCanvasElement",
    "Document",
    "Element",
] }
console_error_panic_hook.workspace = true
console_log.workspace = true
rlobkit-dialogs.workspace = true
